### PR TITLE
NAT-PMP support

### PR DESCRIPTION
**Pull request by pnc**
This is pure garbage please do not merge yet

### CODE REVIEW

**Comment by pnc** [comment]
@bschwind Okay, I taught my editor a special C++ style called `brian` which I think does what you like. Let me know if I missed anything.

Also, so GitHub links these, this addresses #21.

**Comment by pnc** [comment]
@bschwind Hooray! This has a cheap little state machine and error-handling now, so IMO it's ready to merge. I'd be interested to hear what `jetServer` does on your network!

**Comment by pnc** [comment]
I also renamed the class to `PortMapping` since it only represents a single mapping.

**Comment by bschwind** [comment]
Beautiful! Thanks for this. I'll let you know what it does when I run it

**Pull request merged**
